[package]
name = "init"
version = "0.1.0"
edition = "2021"

[dependencies]
minilib = { path = "../minilib" }
kernel_abi = { path = "../../kernel/crates/kernel_abi" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64.workspace = true

